SELECT DATABASE() INTO @db_name FROM DUAL;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats';
SET @query = If( @exists = 1, 'RENAME TABLE cats TO catpages','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_attachments';
SET @query = If( @exists = 1, 'RENAME TABLE cats_attachments TO catpages_pages_attachments','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_comments';
SET @query = If( @exists = 1, 'RENAME TABLE cats_comments TO catpages_pages_comments','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_images';
SET @query = If( @exists = 1, 'RENAME TABLE cats_images TO catpages_pages_images','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_links';
SET @query = If( @exists = 1, 'RENAME TABLE cats_links TO catpages_pages_links','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_pages';
SET @query = If( @exists = 1, 'RENAME TABLE cats_pages TO catpages_pages_pages','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_pages_translations';
SET @query = If( @exists = 1, 'RENAME TABLE cats_pages_translations TO catpages_pages_translations','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_translations';
SET @query = If( @exists = 1, 'RENAME TABLE cats_translations TO catpages_translations','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_related';
SET @query = If( @exists = 1, 'RENAME TABLE cats_related TO catpages_pages_related','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
SELECT COUNT(*) INTO @exists FROM information_schema.tables WHERE table_schema = @db_name AND table_name = 'cats_videos';
SET @query = If( @exists = 1, 'RENAME TABLE cats_videos TO catpages_pages_videos','SELECT \'nothing to rename\' status');
PREPARE stmt FROM @query;
EXECUTE stmt;
UPDATE permalinks SET TableName='catpages' WHERE TableName='cats';
UPDATE permalinks SET TableName='catpages_pages' WHERE TableName='cats_pages';
UPDATE modules_installed SET Version="4.0.0.0" WHERE Module="catpages";
UPDATE modules_installed SET Version="4.0.0.0" WHERE Module="cats";